version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    networks:
      - mynetwork
  app:
    image: my-node-app
    ports:
      - 13000:3000
    networks:
      - mynetwork

networks:
  mynetwork: